settings.primaryColor = "#F7D1E4";
settings.primaryLight = "#FFEBF5";
settings.autocomplete = false;
settings.wordpicture = false;

settings.fsvattributes = {
    lemma: settings.fsvlemma,
    lex: settings.fsvlex,
    posset: settings.posset,
    variants: settings.fsvvariants
};

settings.sdhkstructs = {
    text_id: {
        label: "fulltext",
        pattern: "<a href='http://www.nad.riksarkivet.se/SDHK?EndastDigitaliserat=false&SDHK=<%= val %>&page=1&postid=Dipl_<%= val %>&tab=post' target='_blank'>Riksarkivet <%=val %></a>",
        opts: liteOptions,
        internalSearch: false
    },
    text_lang: { label: "lang" },
    text_place: { label: "city" },
    text_date: { label: "date" },
};

settings.sdhkdescription ='Svenskt Diplomatarium - från <a href="http://www.riksarkivet.se/sdhk" target="_blank">Riksarkivet</a>';

settings.corpora = {};
settings.corporafolders = {};


settings.corporafolders.fsvb = {
    title: "Fornsvenska textbanken",
    contents: ["fsv-profanprosa", "fsv-verser"],
};


settings.corporafolders.fsvb.aldre = {
    title: "Äldre fornsvenska",
    contents: ["fsv-aldrelagar", "fsv-aldrereligiosprosa"]
};

settings.corporafolders.fsvb.yngre = {
    title: "Yngre fornsvenska",
    contents: ["fsv-yngrelagar", "fsv-yngrereligiosprosa", "fsv-yngretankebocker"]
};

settings.corporafolders.fsvb.nysvenska = {
    title: "Nysvenska",
    contents: ["fsv-nysvensklagar", "fsv-nysvenskdalin", "fsv-nysvenskkronikor", "fsv-nysvenskovrigt", "fsv-nysvenskbibel"]
};

settings.corporafolders.medeltid = {
    title: "Medeltidsbrev, Svenskt Diplomatarium",
    contents: ["sdhk-svenska", "sdhk-norska", "sdhk-tyska", "sdhk-latin", "sdhk-ovrigt"],
};

settings.corpora["fsv-aldrelagar"] = fsv_aldrelagar;

settings.corpora["fsv-aldrereligiosprosa"] = {
    morphology: "fsvm",
    id: "fsv-aldrereligiosprosa",
    title: "Äldre religiös prosa – Fornsvenska textbankens material",
    description: settings.fsvdescription,
    within: settings.defaultWithin,
    context: spContext,
    attributes: settings.fsvattributes,
    structAttributes: {
        text_title: {
            label: "title",
            extendedComponent: "datasetSelect",
            dataset: [
                "Birgittaautograferna",
                "Fornsvenska legendariet enligt Codex Bureanus",
                "Pentateuchparafrasen, enligt MB I A",
                "Pentateuchparafrasen B, enligt MB I B",
                "Fornsvenska legendariet enligt Codex Bildstenianus"
            ],
        },
        text_date: {label: "date"}
    }
};

settings.corpora["fsv-profanprosa"] = {
    morphology: "fsvm",
    id: "fsv-profanprosa",
    title: "Profan prosa – Fornsvenska textbankens material",
    description: settings.fsvdescription,
    within: settings.defaultWithin,
    context: spContext,
    attributes: settings.fsvattributes,
    structAttributes: {
        text_title: {
            label: "title",
            extendedComponent: "datasetSelect",
            dataset: [
                "Barlaam och Josaphat, ur Codex Holm A 49 Nådendals klosterbok",
                "Sju vise mästare B, Nådendals klosterbok, Codex Holm A 49",
                "Didrik av Bern, hand A",
                            "Sverige krönika, eller Prosaiska krönikan efter Holm D 26",
                "Konungastyrelsen, Bureus utgåva",
                "Didrik av Bern, hand B",
                "Namnlös och Valentin, ur Codex Holm D 4a",
                "Sju vise mästare C, efter Codex Askabyensis",
                "Historia Trojana, ur Codex Holm D 3a",
                "Sju vise mästare A, ur Codex Holm D 4"
            ]
        },
        text_date: {label: "date"}
    }
};

settings.corpora["fsv-verser"] = {
    morphology: "fsvm",
    id: "fsv-verser",
    title: "Verser – Fornsvenska textbankens material",
    description: settings.fsvdescription,
    within: settings.defaultWithin,
    context: spContext,
    attributes: settings.fsvattributes,
    structAttributes: {
        text_title: {
            label: "title",
            extendedComponent: "datasetSelect",
            dataset: [
                "Fornsvenska Ordspråk",
                "Erikskrönikan, ur Spegelbergs bok, Codex Holm D2" ,
                "Fredrik av Normandie",
                "Ivan Lejonriddaren, ur SFSS Bd 50 Uppsala 1931",
                "Flores och Blanzeflor",
                "Karlskrönikan"
            ]
        },
        text_date: {label: "date"}
    }
};

settings.corpora["fsv-yngrelagar"] = fsv_yngrelagar;

settings.corpora["fsv-yngrereligiosprosa"] = {
    id: "fsv-yngrereligiosprosa",
    morphology: "fsvm",
    title: "Yngre religiös prosa – Fornsvenska textbankens material",
    description: settings.fsvdescription,
    within: settings.defaultWithin,
    context: spContext,
    attributes: settings.fsvattributes,
    structAttributes: {
        text_title: {
            label: "title",
            extendedComponent: "datasetSelect",
            dataset: [
                "Johannes döparens födelse ur Codex Bildstenianus Ups C 528",
                "Jesu lidandes bägare och hans blods utgjutelse",
                "Svenska Medeltidspostillor 1, enligt AM 787",
                "Esthers bok, ur Codex Holm A1",
                "Gregorius av Armenien B, ur Codex Holm A 49 Nådendals klosterbok",
                "Legenden om Sankt Sigfrid, ur Codex Bilstenianus",
                "Legenden om Sankta Jakelina, ur Linköpingslegendariet, Benz 39",
                "S.Johannis Theologi uppenbarelse",
                "Legenden om Sankta Elisabet av Brabant, ur Linköpingslegendariet, Benz 39",
                "Legenden om Sankta Elisabet av Ungern",
                "Legenden om Sankt Joakim, ur Codex Holm A 3",
                "Sankta Anna, enligt Codex Benz 9",
                "Sancta Clara, ur Codex Oxenstiernianus",
                "Sancti Marci Euangelium",
                "Legenden om Sankta Tekla, ur Linköpingslegendariet, Benz 39",
                "Om Erik den helige, efter Codex Vat Reg Lat 525",
                "Legenden om Stephanus påve, ur Linköpingslegendariet, Benz 39, översatt av Herr Jöns Ewangelista",
                "Legenden om Sankt Germanus och Genoveva, ur Codex Holm A 49 Nådendals klosterbok",
                "Legender om Germanus \\(2\\), ur Codex Holm A 49 Nådendals klosterbok",
                "Utdrag ur Legenden om St Mektild, ur Lund Mh 20",
                "Legenden om Sankt Paulus omvändelse, ur Codex Bildstenianus",
                "Legenden om Maria ov Oegnies",
                "Svenska Medeltidspostillor 5, enligt Linc T 181",
                "Legenden om Sankta Felicula och Petronella, ur Linköpingslegendariet, Benz 39'",
                "Legenden om Katarina av Egypten, ur Codex Holm A 3",
                "Svenska Medeltidspostillor 2, enligt Lund Mh 51 och HUB",
                "Legenden om Sankt Alexius ur Linköpingslegendariet",
                "Birgittas uppenbarelser, Sju stycken, fordom i Codex Bergmannius, Lund Mh 20",
                "Birgittas uppenbarelser, återöversättningen, första redaktionen, Bok 7",
                "Sancti Joannisoppenbarilse",
                "Gregorius Stylista, eller Gregorius på stenen, ur Linköpingslegendariet, Benz 39",
                "Själens kloster,översatt av Jöns Budde",
                "Sankt Ansgarii leverne av Rimbertus, ur Codex Holm A 49 Nådendals klosterbok",
                "Vår herres födelse, ur Codex Holm A 3",
                "Bonaventura, kapitel 6",
                "Exodus 16, ur Holm A3",
                "S Stephani saga, ur Linköpingslegendariet, Benz 39, översatt av Johannes Mathei",
                "Ängelens diktamen, ur Codex Oxenstiernianus",
                "Järteckensboken, ur Codex Oxenstiernianus",
                "Gregorius av Armenien A, ur Codex Bergmannius, Lund Mh 20",
                "Legender om Briccius",
                "Legenden om Sankt Macarius Romanus",
                "Legenden om Sankta Amalberga",
                "Legenden om Sankta Phara, ur Linköpingslegendariet, Benz 39",
                "Legenden om Sankta Maria \\(F\\)",
                "Legenden om Sankta Maria \\(E\\), ur Codex Holm A 3",
                "Den heliga Elisabet av Ungerns uppenbarelser A",
                "Patrikssagan, efter Codex Bildstenianus \\(Ups C 528\\)",
                "Bonaventuras betraktelser, Kapitel 7 ur Holm A 3",
                "Sagan om den helige Blasius, ur Codex Oxenstiernianus",
                "Heliga Birgittas uppenbarelser ur Codex Oxenstiernianus",
                "Birgittas uppenbarelser, åttonde boken, ur Cod Holm A 44",
                "Nicodemi evangelium enligt Codex Oxenstiernianus",
                "Apostla gernigar, ur Codex Oxenstiernianus",
                "Judits bok, ur Codex Holm A 1",
                "Lucidarius, redaktion B, ur Holm A 58, Jöns Buddes bok",
                "Sanct Bartholomei moder, eller Kvinnan utan händer, ur Linköpingslegendariet, översatt av Karl Benedictsson",
                "Codex Bildstenianus; strödda legender Hand I",
                "Regula Salvatoris och Revelationes Extravagantes, ur Berlin KB 3762",
                "Legenden om Sankt Albinus",
                "Birgittas uppenbarelser, Birgittinernorska efter Skokloster 5 kvart",
                "Legenden om Erik den helige, ur Codex Bildstenianus Ups C 528",
                "Legenden om Sankta Joleida, ur Linköpingslegendariet, Benz 39",
                "Birgittas uppenbarelser, återöversättingen, andra redaktionen, Bok 4-8",
                "Den heliga Birgittas liv, Vita abbreviata ur Holm A 33",
                "Legenden om Sankta Macra, ur Nådendals klosterbok",
                "Legenden om Johannes Chrysostomus, ur Linköpingslegendariet, Benz 39",
                "Ruths bok, enligt Holm A 1",
                "Legenden om Germanus \\(1b\\), ur Codex Bildstenianus Ups C 528",
                "Elisabet av Ungerns uppenbarelser B",
                "Legender om Genoveva, ur Codex Holm A 49 Nådendals klosterbok",
                "Legenden om Olav den helige, ur Codex Bildstenianus",
                "Stimulus Amoris, efter Cod Holm A 9",
                "Sjusovaresagan, ur Linköpingslegendariet, Benz 39",
                "Katarina av Sverige, ur Codex Holm A 58, Jöns Buddes bok",
                "Legenden om Sankta Rakel, ur Linköpingslegendariet, Benz 39",
                "Birgittas uppenbarelser Bok 1-3, ur Codex Holm A 33",
                "Legeneden om Magnus Jarl av Okenöarna",
                "Bonaventuras betraktelser, Codex Bergmannius, Lund Mh 20",
                "Vitæpatrum - Helga manna lefverne, ur Codex Oxenstiernianus",
                "Legenden om Sankta Otilia, ur Linköpingslegendariet, Benz 39",
                "Heliga Barbara, ur Codex Oxenstiernianus",
                "Legenden om Paulus och Johannes, ur Codex Bildstenianus, hand IV",
                "Själens tröst, ur Codex Holm A 108",
                "Sankt Emerentia och Sankt Anna; översatt från tyska av Lars Elfsson ur Linköpingslegendariet, Benz 39",
                "Karl Magnus, enl Cod Holm D 4",
                "Legenden om Blasius \\(1b\\) ur Ups C 528",
                "Legenden om tre konungar, ur Ups C 528",
                "Legenden om Sankt Servacius",
                "Bonaventuras betraktelser, kapitel 63 ur Holm A 3"
            ],
        },
        text_date: {label: "date"}
    }
};

settings.corpora["fsv-yngretankebocker"] = {
    morphology: "fsvm",
    id: "fsv-yngretankebocker",
    title: "Yngre tänkeböcker – Fornsvenska textbankens material",
    description: settings.fsvdescription,
    within: settings.defaultWithin,
    context: spContext,
    attributes: settings.fsvattributes,
    structAttributes: {
        text_title: {
            label: "title",
            extendedComponent: "datasetSelect",
            dataset: [
                "Läkebok 1: blandad läkedom, ur Codex AM",
                "Läkebok 11: Månaderna, efter KBs handskrift med gammal signatur K 45, supplerad på Danska ur codex Grensholmensis",
                "Läkebok, 8 ur codex Grensholmensis i Linköping",
                "Läkebok 4, ur Codex Holm A 49",
                "Läkebok 2, ur pappershandskriften Ups C 601",
                "Bondakonst av Peder Månsson",
                                "Läkedomar, codex Ups Benz 22",
                "Läkebok 5 och 6, ur Codex 19 Benz",
                "Läkebok 7, efter Codex linc M 5",
                "Läkebok 10: Zoodiaken, månaderna m m, efter hskr i Rålambska samlingen",
                "Läkedom, efter Peder Månssons handskrift i Linköpings Stiftsbibliotek"
            ],
        },
        text_date: {label: "date"}
    }
};

settings.corpora["fsv-nysvenskbibel"] = {
    id: "fsv-nysvenskbibel",
    title: "Nysvenska bibelböcker – Fornsvenska textbankens material",
    description: settings.fsvdescription,
    within: settings.defaultWithin,
    context: spContext,
    attributes: {pos: attrs.pos},
    structAttributes: {
        text_title: {
            label: "title",
            extendedComponent: "datasetSelect",
            dataset: [
                "Gustav Vasas Bibel, Markusevanguliet",
                "Gustav Vasas Bibel, Lukasevangeliet"
            ]
        },
        text_date: {label: "date"}
    }
};

settings.corpora["fsv-nysvenskdalin"] = {
    id: "fsv-nysvenskdalin",
    title: "Dalin: then swänska argus – Fornsvenska textbankens material",
    description: settings.fsvdescription,
    within: settings.defaultWithin,
    context: spContext,
    attributes: {pos: attrs.pos},
    structAttributes: {
        text_title: {
            label: "title",
            extendedComponent: "datasetSelect",
            dataset: [
                "Dalin: Then Swänska Argus"
            ],
        },
        text_date: {label: "date"}
    }
};

settings.corpora["fsv-nysvenskkronikor"] = {
    id: "fsv-nysvenskkronikor",
    title: "Nysvenska krönikor – Fornsvenska textbankens material",
    description: settings.fsvdescription,
    within: settings.defaultWithin,
    context: spContext,
    attributes: {pos: attrs.pos},
    structAttributes: {
        text_title: {
            label: "title",
            extendedComponent: "datasetSelect",
            dataset: [
                "Peder Swarts krönika",
                "Per Brahes krönika",
                "Olaus Petris Krönika, stil B",
                "Olaus Petris Krönika, stil A",
                "Olaus Petris Krönika"
            ],
        },
        text_date: {label: "date"}
    }
};

settings.corpora["fsv-nysvenskovrigt"] = {
    id: "fsv-nysvenskovrigt",
    title: "Nysvenska, övrigt – Fornsvenska textbankens material",
    description: settings.fsvdescription,
    within: settings.defaultWithin,
    context: spContext,
    attributes: {pos: attrs.pos},
    structAttributes: {
        text_title: {
            label: "title",

            dataset: [
                "Runius: Prosastycken",
                "Mag. Joh. Qvirfelds himmelska örtegårds-sällskap",
                "Gyllenborg: Svenska sprätthöken",
                "Jon Stålhammars brev",
                "Agneta Horns levnadsbeskrivning",
                "Beskrifning öfwer Sweriges Lapmarker 1747 av Pehr Högström, kap 1-4",
                "AnnaVasas brev",
                "Carl Carlsson Gyllenhielms anteckningar",
                "Samuel Columbus: Mål-roo eller Roo-mål",
                "Haqvin Spegel: Dagbok",
                "UrbanHiärne: Stratonice"
            ],
        },
        text_date: {label: "date"}
    }
};

settings.corpora["fsv-nysvensklagar"] = {
    id: "fsv-nysvensklagar",
    title: "Nysvenska lagar – Fornsvenska textbankens material",
    description: settings.fsvdescription,
    within: settings.defaultWithin,
    context: spContext,
    attributes: {
    	pos: attrs.pos
    },
    structAttributes: {
        text_title: {
            label: "title",

            dataset: [
                "Missgiernings Balk",
                "Giftermåls balk \\(1734\\)",
            ],
        },
        text_date: {label: "date"}
    }
};

settings.corpora["sdhk-svenska"] = {
    id: "sdhk-svenska",
    title: "Medeltidsbrev - Svenska",
    description: settings.sdhkdescription,
    within: settings.defaultWithin,
    context: defaultContext,
    attributes: {},
    structAttributes: settings.sdhkstructs
};

settings.corpora["sdhk-norska"] = {
    id: "sdhk-norska",
    title: "Medeltidsbrev - Norska",
    description: settings.sdhkdescription,
    within: settings.defaultWithin,
    context: defaultContext,
    attributes: {},
    structAttributes: settings.sdhkstructs
};

settings.corpora["sdhk-tyska"] = {
    id: "sdhk-tyska",
    title: "Medeltidsbrev - Tyska",
    description: settings.sdhkdescription,
    within: settings.defaultWithin,
    context: defaultContext,
    attributes: {},
    structAttributes: settings.sdhkstructs
};

settings.corpora["sdhk-latin"] = {
    id: "sdhk-latin",
    title: "Medeltidsbrev - Latin",
    description: settings.sdhkdescription,
    within: settings.defaultWithin,
    context: defaultContext,
    attributes: {},
    structAttributes: settings.sdhkstructs
};

settings.corpora["sdhk-ovrigt"] = {
    id: "sdhk-ovrigt",
    title: "Medeltidsbrev - Övriga språk",
    description: settings.sdhkdescription,
    within: settings.defaultWithin,
    context: defaultContext,
    attributes: {},
    structAttributes: settings.sdhkstructs
};

if(isLab){
    settings.corpora["ogl"] = {
        id: "ogl",
        title: "Östgötalagen",
        description: "",
        within: settings.defaultWithin,
        context: {"1 section": "1 section"},
        attributes: {
            baseform: {
                label: "baseform",
                type: "set",
                extendedTemplate: "<input ng-model='model' >",
                opts: setOptions,
                externalSearch: "http://spraakbanken.gu.se/karplabb/#?resources=soederwall,soederwall-supp&search=extended%7C%7Cand%7Cgf%7Cequals%7C<%= val %>&searchTab=extended&hpp=25&extended=and%7Cgf%7Cequals%7C<%= val %>",
            },
            pos: {
                label: "pos",
                opts: liteOptions,
                extendedComponent: "datasetSelect",
                translation: {
                    "Nb": "substantiv",
                    "Ne": "egennamn",
                    "A-": "adjektiv",
                    "Pp": "pronomen, personligt",
                    "Pk": "pronomen, reflexivt",
                    "Pi": "pronomen, interrogativt",
                    "Px": "pronomen, indefinit",
                    "Pd": "determinerare, demonstrativ",
                    "Py": "determinerare, kvantor",
                    "Ps": "determinerare, possessiv",
                    "V-": "verb",
                    "Df": "adverb",
                    "Du": "adverb, interrogativ",
                    "R-": "preposition",
                    "C-": "samordnare",
                    "G-": "underordnare",
                    "N-": "infinitivmärke",
                    "I-": "interjektion",
                    "X-": "icke-analyserat",
                    "F-": "främmande ord"
                },
                dataset: [
                    "Nb",
                    "Ne",
                    "A-",
                    "Pp",
                    "Pk",
                    "Pi",
                    "Px",
                    "Pd",
                    "Py",
                    "Ps",
                    "V-",
                    "Df",
                    "Du",
                    "R-",
                    "C-",
                    "G-",
                    "N-",
                    "I-",
                    "X-",
                    "F-"
                ]
            },
            morph: {
                label: "msd",
                opts: liteOptions,
                extendedComponent: "datasetSelect",
                translation: {
                    "A----------n": "adjektiv oböjlig",
                    "A--s---mnpsi": "adjektiv singularis maskulinum nominativ positiv indefinit",
                    "A--s---mnpti": "adjektiv singularis maskulinum nominativ positiv oklart species",
                    "A--s---mncsi": "adjektiv singularis maskulinum nominativ komparativ indefinit",
                    "A--s---mncti": "adjektiv singularis maskulinum nominativ komparativ oklart species",
                    "A--s---mnssi": "adjektiv singularis maskulinum nominativ superlativ indefinit",
                    "A--s---mnswi": "adjektiv singularis maskulinum nominativ superlativ definit",
                    "A--s---mnsti": "adjektiv singularis maskulinum nominativ superlativ oklart species",
                    "A--s---mgpwi": "adjektiv singularis maskulinum genitiv positiv definit",
                    "A--s---mgpti": "adjektiv singularis maskulinum genitiv positiv oklart species",
                    "A--s---mgcti": "adjektiv singularis maskulinum genitiv komparativ oklart species",
                    "A--s---mdpti": "adjektiv singularis maskulinum dativ positiv oklart species",
                    "A--s---mapsi": "adjektiv singularis maskulinum ackusativ positiv indefinit",
                    "A--s---mapti": "adjektiv singularis maskulinum ackusativ positiv oklart species",
                    "A--s---macwi": "adjektiv singularis maskulinum ackusativ komparativ definit",
                    "A--s---macti": "adjektiv singularis maskulinum ackusativ komparativ oklart species",
                    "A--s---mxpsi": "adjektiv singularis maskulinum oklart kasus positiv indefinit",
                    "A--s---mxpti": "adjektiv singularis maskulinum oklart kasus positiv oklart species",
                    "A--s---mxcti": "adjektiv singularis maskulinum oklart kasus komparativ oklart species",
                    "A--s---mxsti": "adjektiv singularis maskulinum oklart kasus superlativ oklart species",
                    "A--s---fnpsi": "adjektiv singularis femininum nominativ positiv indefinit",
                    "A--s---fnpwi": "adjektiv singularis femininum nominativ positiv definit",
                    "A--s---fnpti": "adjektiv singularis femininum nominativ positiv oklart species",
                    "A--s---fncti": "adjektiv singularis femininum nominativ komparativ oklart species",
                    "A--s---fnsti": "adjektiv singularis femininum nominativ superlativ oklart species",
                    "A--s---fgpti": "adjektiv singularis femininum genitiv positiv oklart species",
                    "A--s---fdpti": "adjektiv singularis femininum dativ positiv oklart species",
                    "A--s---fapsi": "adjektiv singularis femininum ackusativ positiv indefinit",
                    "A--s---fapti": "adjektiv singularis femininum ackusativ positiv oklart species",
                    "A--s---facti": "adjektiv singularis femininum ackusativ komparativ oklart species",
                    "A--s---fxpti": "adjektiv singularis femininum oklart kasus positiv oklart species",
                    "A--s---fxcti": "adjektiv singularis femininum oklart kasus komparativ oklart species",
                    "A--s---nnpsi": "adjektiv singularis neutrum nominativ positiv indefinit",
                    "A--s---nnpwi": "adjektiv singularis neutrum nominativ positiv definit",
                    "A--s---nnpti": "adjektiv singularis neutrum nominativ positiv oklart species",
                    "A--s---nncti": "adjektiv singularis neutrum nominativ komparativ oklart species",
                    "A--s---nnsti": "adjektiv singularis neutrum nominativ superlativ oklart species",
                    "A--s---ngpti": "adjektiv singularis neutrum genitiv positiv oklart species",
                    "A--s---ndpti": "adjektiv singularis neutrum dativ positiv oklart species",
                    "A--s---ndsti": "adjektiv singularis neutrum dativ superlativ oklart species",
                    "A--s---napsi": "adjektiv singularis neutrum ackusativ positiv indefinit",
                    "A--s---napti": "adjektiv singularis neutrum ackusativ positiv oklart species",
                    "A--s---nacti": "adjektiv singularis neutrum ackusativ komparativ oklart species",
                    "A--s---nxpti": "adjektiv singularis neutrum oklart kasus positiv oklart species",
                    "A--s---nxsti": "adjektiv singularis neutrum oklart kasus superlativ oklart species",
                    "A--s---pdpti": "adjektiv singularis utrum dativ positiv oklart species",
                    "A--s---odpti": "adjektiv singularis icke-femininum dativ positiv oklart species",
                    "A--s---xnpti": "adjektiv singularis oklart genus nominativ positiv oklart species",
                    "A--s---xgpti": "adjektiv singularis oklart genus genitiv positiv oklart species",
                    "A--s---xdpti": "adjektiv singularis oklart genus dativ positiv oklart species",
                    "A--s---xapti": "adjektiv singularis oklart genus ackusativ positiv oklart species",
                    "A--s---xxpti": "adjektiv singularis oklart genus oklart kasus positiv oklart species",
                    "A--p---mnpsi": "adjektiv pluralis maskulinum nominativ positiv indefinit",
                    "A--p---mnpti": "adjektiv pluralis maskulinum nominativ positiv oklart species",
                    "A--p---mncti": "adjektiv pluralis maskulinum nominativ komparativ oklart species",
                    "A--p---mgpti": "adjektiv pluralis maskulinum genitiv positiv oklart species",
                    "A--p---mdpti": "adjektiv pluralis maskulinum dativ positiv oklart species",
                    "A--p---mdcti": "adjektiv pluralis maskulinum dativ komparativ oklart species",
                    "A--p---mapti": "adjektiv pluralis maskulinum ackusativ positiv oklart species",
                    "A--p---masti": "adjektiv pluralis maskulinum ackusativ superlativ oklart species",
                    "A--p---mxpsi": "adjektiv pluralis maskulinum oklart kasus positiv indefinit",
                    "A--p---fnpti": "adjektiv pluralis femininum nominativ positiv oklart species",
                    "A--p---fdpsi": "adjektiv pluralis femininum dativ positiv indefinit",
                    "A--p---fdpti": "adjektiv pluralis femininum dativ positiv oklart species",
                    "A--p---fapsi": "adjektiv pluralis femininum ackusativ positiv indefinit",
                    "A--p---fapti": "adjektiv pluralis femininum ackusativ positiv oklart species",
                    "A--p---facti": "adjektiv pluralis femininum ackusativ komparativ oklart species",
                    "A--p---fxpti": "adjektiv pluralis femininum oklart kasus positiv oklart species",
                    "A--p---nnpti": "adjektiv pluralis neutrum nominativ positiv oklart species",
                    "A--p---nncti": "adjektiv pluralis neutrum nominativ komparativ oklart species",
                    "A--p---ndpsi": "adjektiv pluralis neutrum dativ positiv indefinit",
                    "A--p---ndpti": "adjektiv pluralis neutrum dativ positiv oklart species",
                    "A--p---ndsti": "adjektiv pluralis neutrum dativ superlativ oklart species",
                    "A--p---napsi": "adjektiv pluralis neutrum ackusativ positiv indefinit",
                    "A--p---napti": "adjektiv pluralis neutrum ackusativ positiv oklart species",
                    "A--p---nacti": "adjektiv pluralis neutrum ackusativ komparativ oklart species",
                    "A--p---pncsi": "adjektiv pluralis utrum nominativ komparativ indefinit",
                    "A--p---ogpti": "adjektiv pluralis icke-femininum genitiv positiv oklart species",
                    "A--p---rdpti": "adjektiv pluralis icke-maskulinum dativ positiv oklart species",
                    "A--p---xnpti": "adjektiv pluralis oklart genus nominativ positiv oklart species",
                    "A--p---xdpsi": "adjektiv pluralis oklart genus dativ positiv indefinit",
                    "A--x---mnpti": "adjektiv oklart numerus maskulinum nominativ positiv oklart species",
                    "A--x---mgpti": "adjektiv oklart numerus maskulinum genitiv positiv oklart species",
                    "A--x---mapti": "adjektiv oklart numerus maskulinum ackusativ positiv oklart species",
                    "A--x---mxpti": "adjektiv oklart numerus maskulinum oklart kasus positiv oklart species",
                    "A--x---fxpti": "adjektiv oklart numerus femininum oklart kasus positiv oklart species",
                    "A--x---napti": "adjektiv oklart numerus neutrum ackusativ positiv oklart species",
                    "A--x---xxpsi": "adjektiv oklart numerus oklart genus oklart kasus positiv indefinit",
                    "A--x---xxpti": "adjektiv oklart numerus oklart genus oklart kasus positiv oklart species",
                    "C----------n": "samordnare oböjlig",
                    "Df---------n": "adverb oböjlig",
                    "Df-------p-i": "adverb positiv",
                    "Df-------c-i": "adverb komparativ",
                    "Df-------s-i": "adverb superlativ",
                    "Df-------x-i": "adverb oklar grad",
                    "Du---------n": "adverb, interrogativ oböjlig",
                    "F----------n": "främmande ord oböjlig",
                    "G----------n": "underordnare oböjlig",
                    "I----------n": "interjektion oböjlig",
                    "Nb-s---mn-si": "substantiv singularis maskulinum nominativ indefinit",
                    "Nb-s---mn-wi": "substantiv singularis maskulinum nominativ definit",
                    "Nb-s---mn-ti": "substantiv singularis maskulinum nominativ oklart species",
                    "Nb-s---mg-si": "substantiv singularis maskulinum genitiv indefinit",
                    "Nb-s---mg-wi": "substantiv singularis maskulinum genitiv definit",
                    "Nb-s---mg-ti": "substantiv singularis maskulinum genitiv oklart species",
                    "Nb-s---md-si": "substantiv singularis maskulinum dativ indefinit",
                    "Nb-s---md-wi": "substantiv singularis maskulinum dativ definit",
                    "Nb-s---md-ti": "substantiv singularis maskulinum dativ oklart species",
                    "Nb-s---ma-si": "substantiv singularis maskulinum ackusativ indefinit",
                    "Nb-s---ma-wi": "substantiv singularis maskulinum ackusativ definit",
                    "Nb-s---ma-ti": "substantiv singularis maskulinum ackusativ oklart species",
                    "Nb-s---mx-si": "substantiv singularis maskulinum oklart kasus indefinit",
                    "Nb-s---mx-ti": "substantiv singularis maskulinum oklart kasus oklart species",
                    "Nb-s---fn-si": "substantiv singularis femininum nominativ indefinit",
                    "Nb-s---fn-wi": "substantiv singularis femininum nominativ definit",
                    "Nb-s---fn-ti": "substantiv singularis femininum nominativ oklart species",
                    "Nb-s---fg-si": "substantiv singularis femininum genitiv indefinit",
                    "Nb-s---fg-wi": "substantiv singularis femininum genitiv definit",
                    "Nb-s---fg-ti": "substantiv singularis femininum genitiv oklart species",
                    "Nb-s---fd-si": "substantiv singularis femininum dativ indefinit",
                    "Nb-s---fd-wi": "substantiv singularis femininum dativ definit",
                    "Nb-s---fd-ti": "substantiv singularis femininum dativ oklart species",
                    "Nb-s---fa-si": "substantiv singularis femininum ackusativ indefinit",
                    "Nb-s---fa-wi": "substantiv singularis femininum ackusativ definit",
                    "Nb-s---fa-ti": "substantiv singularis femininum ackusativ oklart species",
                    "Nb-s---fx-si": "substantiv singularis femininum oklart kasus indefinit",
                    "Nb-s---fx-ti": "substantiv singularis femininum oklart kasus oklart species",
                    "Nb-s---nn-si": "substantiv singularis neutrum nominativ indefinit",
                    "Nb-s---nn-wi": "substantiv singularis neutrum nominativ definit",
                    "Nb-s---nn-ti": "substantiv singularis neutrum nominativ oklart species",
                    "Nb-s---ng-si": "substantiv singularis neutrum genitiv indefinit",
                    "Nb-s---ng-ti": "substantiv singularis neutrum genitiv oklart species",
                    "Nb-s---nd-si": "substantiv singularis neutrum dativ indefinit",
                    "Nb-s---nd-wi": "substantiv singularis neutrum dativ definit",
                    "Nb-s---nd-ti": "substantiv singularis neutrum dativ oklart species",
                    "Nb-s---na-si": "substantiv singularis neutrum ackusativ indefinit",
                    "Nb-s---na-wi": "substantiv singularis neutrum ackusativ definit",
                    "Nb-s---na-ti": "substantiv singularis neutrum ackusativ oklart species",
                    "Nb-s---nx-si": "substantiv singularis neutrum oklart kasus indefinit",
                    "Nb-s---nx-ti": "substantiv singularis neutrum oklart kasus oklart species",
                    "Nb-s---pn-ti": "substantiv singularis utrum nominativ oklart species",
                    "Nb-s---pg-ti": "substantiv singularis utrum genitiv oklart species",
                    "Nb-s---pa-si": "substantiv singularis utrum ackusativ indefinit",
                    "Nb-s---pa-ti": "substantiv singularis utrum ackusativ oklart species",
                    "Nb-s---px-ti": "substantiv singularis utrum oklart kasus oklart species",
                    "Nb-s---on-ti": "substantiv singularis icke-femininum nominativ oklart species",
                    "Nb-s---og-ti": "substantiv singularis icke-femininum genitiv oklart species",
                    "Nb-s---od-ti": "substantiv singularis icke-femininum dativ oklart species",
                    "Nb-s---oa-ti": "substantiv singularis icke-femininum ackusativ oklart species",
                    "Nb-s---ox-ti": "substantiv singularis icke-femininum oklart kasus oklart species",
                    "Nb-s---rn-ti": "substantiv singularis icke-maskulinum nominativ oklart species",
                    "Nb-s---ra-ti": "substantiv singularis icke-maskulinum ackusativ oklart species",
                    "Nb-s---rx-ti": "substantiv singularis icke-maskulinum oklart kasus oklart species",
                    "Nb-s---xn-ti": "substantiv singularis oklart genus nominativ oklart species",
                    "Nb-s---xg-si": "substantiv singularis oklart genus genitiv indefinit",
                    "Nb-s---xg-ti": "substantiv singularis oklart genus genitiv oklart species",
                    "Nb-s---xa-ti": "substantiv singularis oklart genus ackusativ oklart species",
                    "Nb-p---mn-si": "substantiv pluralis maskulinum nominativ indefinit",
                    "Nb-p---mn-wi": "substantiv pluralis maskulinum nominativ definit",
                    "Nb-p---mn-ti": "substantiv pluralis maskulinum nominativ oklart species",
                    "Nb-p---mg-wi": "substantiv pluralis maskulinum genitiv definit",
                    "Nb-p---mg-ti": "substantiv pluralis maskulinum genitiv oklart species",
                    "Nb-p---md-si": "substantiv pluralis maskulinum dativ indefinit",
                    "Nb-p---md-wi": "substantiv pluralis maskulinum dativ definit",
                    "Nb-p---md-ti": "substantiv pluralis maskulinum dativ oklart species",
                    "Nb-p---ma-si": "substantiv pluralis maskulinum ackusativ indefinit",
                    "Nb-p---ma-ti": "substantiv pluralis maskulinum ackusativ oklart species",
                    "Nb-p---mx-si": "substantiv pluralis maskulinum oklart kasus indefinit",
                    "Nb-p---mx-ti": "substantiv pluralis maskulinum oklart kasus oklart species",
                    "Nb-p---fn-si": "substantiv pluralis femininum nominativ indefinit",
                    "Nb-p---fn-ti": "substantiv pluralis femininum nominativ oklart species",
                    "Nb-p---fg-ti": "substantiv pluralis femininum genitiv oklart species",
                    "Nb-p---fd-si": "substantiv pluralis femininum dativ indefinit",
                    "Nb-p---fd-ti": "substantiv pluralis femininum dativ oklart species",
                    "Nb-p---fa-si": "substantiv pluralis femininum ackusativ indefinit",
                    "Nb-p---fa-wi": "substantiv pluralis femininum ackusativ definit",
                    "Nb-p---fa-ti": "substantiv pluralis femininum ackusativ oklart species",
                    "Nb-p---fx-ti": "substantiv pluralis femininum oklart kasus oklart species",
                    "Nb-p---nn-si": "substantiv pluralis neutrum nominativ indefinit",
                    "Nb-p---nn-wi": "substantiv pluralis neutrum nominativ definit",
                    "Nb-p---nn-ti": "substantiv pluralis neutrum nominativ oklart species",
                    "Nb-p---ng-si": "substantiv pluralis neutrum genitiv indefinit",
                    "Nb-p---ng-wi": "substantiv pluralis neutrum genitiv definit",
                    "Nb-p---ng-ti": "substantiv pluralis neutrum genitiv oklart species",
                    "Nb-p---nd-si": "substantiv pluralis neutrum dativ indefinit",
                    "Nb-p---nd-wi": "substantiv pluralis neutrum dativ definit",
                    "Nb-p---nd-ti": "substantiv pluralis neutrum dativ oklart species",
                    "Nb-p---na-si": "substantiv pluralis neutrum ackusativ indefinit",
                    "Nb-p---na-wi": "substantiv pluralis neutrum ackusativ definit",
                    "Nb-p---na-ti": "substantiv pluralis neutrum ackusativ oklart species",
                    "Nb-p---nx-si": "substantiv pluralis neutrum oklart kasus indefinit",
                    "Nb-p---nx-ti": "substantiv pluralis neutrum oklart kasus oklart species",
                    "Nb-p---pd-ti": "substantiv pluralis utrum dativ oklart species",
                    "Nb-p---pa-si": "substantiv pluralis utrum ackusativ indefinit",
                    "Nb-p---pa-ti": "substantiv pluralis utrum ackusativ oklart species",
                    "Nb-p---on-si": "substantiv pluralis icke-femininum nominativ indefinit",
                    "Nb-p---on-ti": "substantiv pluralis icke-femininum nominativ oklart species",
                    "Nb-p---og-ti": "substantiv pluralis icke-femininum genitiv oklart species",
                    "Nb-p---od-wi": "substantiv pluralis icke-femininum dativ definit",
                    "Nb-p---od-ti": "substantiv pluralis icke-femininum dativ oklart species",
                    "Nb-p---rd-si": "substantiv pluralis icke-maskulinum dativ indefinit",
                    "Nb-p---rd-ti": "substantiv pluralis icke-maskulinum dativ oklart species",
                    "Nb-x---mn-ti": "substantiv oklart numerus maskulinum nominativ oklart species",
                    "Nb-x---mg-si": "substantiv oklart numerus maskulinum genitiv indefinit",
                    "Nb-x---md-si": "substantiv oklart numerus maskulinum dativ indefinit",
                    "Nb-x---md-ti": "substantiv oklart numerus maskulinum dativ oklart species",
                    "Nb-x---ma-ti": "substantiv oklart numerus maskulinum ackusativ oklart species",
                    "Nb-x---mx-ti": "substantiv oklart numerus maskulinum oklart kasus oklart species",
                    "Nb-x---fg-ti": "substantiv oklart numerus femininum genitiv oklart species",
                    "Nb-x---fa-ti": "substantiv oklart numerus femininum ackusativ oklart species",
                    "Nb-x---fx-ti": "substantiv oklart numerus femininum oklart kasus oklart species",
                    "Nb-x---nn-si": "substantiv oklart numerus neutrum nominativ indefinit",
                    "Nb-x---nn-ti": "substantiv oklart numerus neutrum nominativ oklart species",
                    "Nb-x---ng-ti": "substantiv oklart numerus neutrum genitiv oklart species",
                    "Nb-x---na-si": "substantiv oklart numerus neutrum ackusativ indefinit",
                    "Nb-x---na-ti": "substantiv oklart numerus neutrum ackusativ oklart species",
                    "Nb-x---nx-ti": "substantiv oklart numerus neutrum oklart kasus oklart species",
                    "Nb-x---ox-ti": "substantiv oklart numerus icke-femininum oklart kasus oklart species",
                    "Ne---------n": "egennamn oböjlig",
                    "Ne-s---mn-ti": "egennamn singularis maskulinum nominativ oklart species",
                    "Ne-s---mg-ti": "egennamn singularis maskulinum genitiv oklart species",
                    "Ne-s---md-si": "egennamn singularis maskulinum dativ indefinit",
                    "Ne-s---fd-si": "egennamn singularis femininum dativ indefinit",
                    "Ne-s---xg-ti": "egennamn singularis oklart genus genitiv oklart species",
                    "Ne-s---xd-ti": "egennamn singularis oklart genus dativ oklart species",
                    "Pd-s---mn--i": "determinerare, demonstrativ singularis maskulinum nominativ",
                    "Pd-s---mg--i": "determinerare, demonstrativ singularis maskulinum genitiv",
                    "Pd-s---md--i": "determinerare, demonstrativ singularis maskulinum dativ",
                    "Pd-s---ma--i": "determinerare, demonstrativ singularis maskulinum ackusativ",
                    "Pd-s---mx--i": "determinerare, demonstrativ singularis maskulinum oklart kasus",
                    "Pd-s---fn--i": "determinerare, demonstrativ singularis femininum nominativ",
                    "Pd-s---fg--i": "determinerare, demonstrativ singularis femininum genitiv",
                    "Pd-s---fd--i": "determinerare, demonstrativ singularis femininum dativ",
                    "Pd-s---fa--i": "determinerare, demonstrativ singularis femininum ackusativ",
                    "Pd-s---fx--i": "determinerare, demonstrativ singularis femininum oklart kasus",
                    "Pd-s---nn--i": "determinerare, demonstrativ singularis neutrum nominativ",
                    "Pd-s---ng--i": "determinerare, demonstrativ singularis neutrum genitiv",
                    "Pd-s---nd--i": "determinerare, demonstrativ singularis neutrum dativ",
                    "Pd-s---na--i": "determinerare, demonstrativ singularis neutrum ackusativ",
                    "Pd-s---nx--i": "determinerare, demonstrativ singularis neutrum oklart kasus",
                    "Pd-s---od--i": "determinerare, demonstrativ singularis icke-femininum dativ",
                    "Pd-s---xn--i": "determinerare, demonstrativ singularis oklart genus nominativ",
                    "Pd-s---xg--i": "determinerare, demonstrativ singularis oklart genus genitiv",
                    "Pd-s---xx--i": "determinerare, demonstrativ singularis oklart genus oklart kasus",
                    "Pd-p---mn--i": "determinerare, demonstrativ pluralis maskulinum nominativ",
                    "Pd-p---mg--i": "determinerare, demonstrativ pluralis maskulinum genitiv",
                    "Pd-p---md--i": "determinerare, demonstrativ pluralis maskulinum dativ",
                    "Pd-p---ma--i": "determinerare, demonstrativ pluralis maskulinum ackusativ",
                    "Pd-p---mx--i": "determinerare, demonstrativ pluralis maskulinum oklart kasus",
                    "Pd-p---fn--i": "determinerare, demonstrativ pluralis femininum nominativ",
                    "Pd-p---fg--i": "determinerare, demonstrativ pluralis femininum genitiv",
                    "Pd-p---fd--i": "determinerare, demonstrativ pluralis femininum dativ",
                    "Pd-p---fa--i": "determinerare, demonstrativ pluralis femininum ackusativ",
                    "Pd-p---nn--i": "determinerare, demonstrativ pluralis neutrum nominativ",
                    "Pd-p---ng--i": "determinerare, demonstrativ pluralis neutrum genitiv",
                    "Pd-p---nd--i": "determinerare, demonstrativ pluralis neutrum dativ",
                    "Pd-p---na--i": "determinerare, demonstrativ pluralis neutrum ackusativ",
                    "Pd-p---pn--i": "determinerare, demonstrativ pluralis utrum nominativ",
                    "Pd-p---pg--i": "determinerare, demonstrativ pluralis utrum genitiv",
                    "Pd-p---on--i": "determinerare, demonstrativ pluralis icke-femininum nominativ",
                    "Pd-p---xn--i": "determinerare, demonstrativ pluralis oklart genus nominativ",
                    "Pd-p---xg--i": "determinerare, demonstrativ pluralis oklart genus genitiv",
                    "Pd-p---xd--i": "determinerare, demonstrativ pluralis oklart genus dativ",
                    "Pd-p---xa--i": "determinerare, demonstrativ pluralis oklart genus ackusativ",
                    "Pd-x---mn--i": "determinerare, demonstrativ oklart numerus maskulinum nominativ",
                    "Pd-x---mg--i": "determinerare, demonstrativ oklart numerus maskulinum genitiv",
                    "Pd-x---mx--i": "determinerare, demonstrativ oklart numerus maskulinum oklart kasus",
                    "Pd-x---fg--i": "determinerare, demonstrativ oklart numerus femininum genitiv",
                    "Pd-x---nx--i": "determinerare, demonstrativ oklart numerus neutrum oklart kasus",
                    "Pd-x---xd--i": "determinerare, demonstrativ oklart numerus oklart genus dativ",
                    "Pi-s---na--i": "pronomen, interrogativt singularis neutrum ackusativ",
                    "Pi-s---xn--i": "pronomen, interrogativt singularis oklart genus nominativ",
                    "Pi-s---xx--i": "pronomen, interrogativt singularis oklart genus oklart kasus",
                    "Pi-s----n--i": "pronomen, interrogativt singularis nominativ",
                    "Pi-s----a--i": "pronomen, interrogativt singularis ackusativ",
                    "Pi-s----x--i": "pronomen, interrogativt singularis oklart kasus",
                    "Pi-p----x--i": "pronomen, interrogativt pluralis oklart kasus",
                    "Pk-s----n--i": "pronomen, reflexivt singularis nominativ",
                    "Pk-s----g--i": "pronomen, reflexivt singularis genitiv",
                    "Pk-s----d--i": "pronomen, reflexivt singularis dativ",
                    "Pk-s----a--i": "pronomen, reflexivt singularis ackusativ",
                    "Pk-s----x--i": "pronomen, reflexivt singularis oklart kasus",
                    "Pk-p----n--i": "pronomen, reflexivt pluralis nominativ",
                    "Pp-s----n--i": "pronomen, personligt singularis nominativ",
                    "Pp-s----g--i": "pronomen, personligt singularis genitiv",
                    "Pp-s----d--i": "pronomen, personligt singularis dativ",
                    "Pp-s----a--i": "pronomen, personligt singularis ackusativ",
                    "Pp-p----n--i": "pronomen, personligt pluralis nominativ",
                    "Pp-p----g--i": "pronomen, personligt pluralis genitiv",
                    "Pp-p----d--i": "pronomen, personligt pluralis dativ",
                    "Pp-p----a--i": "pronomen, personligt pluralis ackusativ",
                    "Pp-x----n--i": "pronomen, personligt oklart numerus nominativ",
                    "Ps-s----n--i": "determinerare, possessiv singularis nominativ",
                    "Ps-s----g--i": "determinerare, possessiv singularis genitiv",
                    "Ps-s----d--i": "determinerare, possessiv singularis dativ",
                    "Ps-s----a--i": "determinerare, possessiv singularis ackusativ",
                    "Ps-s----x--i": "determinerare, possessiv singularis oklart kasus",
                    "Ps-p----g--i": "determinerare, possessiv pluralis genitiv",
                    "Ps-p----d--i": "determinerare, possessiv pluralis dativ",
                    "Ps-p----a--i": "determinerare, possessiv pluralis ackusativ",
                    "Ps-p----x--i": "determinerare, possessiv pluralis oklart kasus",
                    "Ps-x----x--i": "determinerare, possessiv oklart numerus oklart kasus",
                    "Px-s---mn--i": "pronomen, indefinit singularis maskulinum nominativ",
                    "Px-s---mg--i": "pronomen, indefinit singularis maskulinum genitiv",
                    "Px-s---md--i": "pronomen, indefinit singularis maskulinum dativ",
                    "Px-s---ma--i": "pronomen, indefinit singularis maskulinum ackusativ",
                    "Px-s---mx--i": "pronomen, indefinit singularis maskulinum oklart kasus",
                    "Px-s---fn--i": "pronomen, indefinit singularis femininum nominativ",
                    "Px-s---fd--i": "pronomen, indefinit singularis femininum dativ",
                    "Px-s---fa--i": "pronomen, indefinit singularis femininum ackusativ",
                    "Px-s---fx--i": "pronomen, indefinit singularis femininum oklart kasus",
                    "Px-s---nn--i": "pronomen, indefinit singularis neutrum nominativ",
                    "Px-s---ng--i": "pronomen, indefinit singularis neutrum genitiv",
                    "Px-s---nd--i": "pronomen, indefinit singularis neutrum dativ",
                    "Px-s---na--i": "pronomen, indefinit singularis neutrum ackusativ",
                    "Px-s---nx--i": "pronomen, indefinit singularis neutrum oklart kasus",
                    "Px-s---pn--i": "pronomen, indefinit singularis utrum nominativ",
                    "Px-s---rd--i": "pronomen, indefinit singularis icke-maskulinum dativ",
                    "Px-s---xn--i": "pronomen, indefinit singularis oklart genus nominativ",
                    "Px-s---xg--i": "pronomen, indefinit singularis oklart genus genitiv",
                    "Px-p---mn--i": "pronomen, indefinit pluralis maskulinum nominativ",
                    "Px-p---md--i": "pronomen, indefinit pluralis maskulinum dativ",
                    "Px-p---ma--i": "pronomen, indefinit pluralis maskulinum ackusativ",
                    "Px-p---fn--i": "pronomen, indefinit pluralis femininum nominativ",
                    "Px-p---fd--i": "pronomen, indefinit pluralis femininum dativ",
                    "Px-p---fa--i": "pronomen, indefinit pluralis femininum ackusativ",
                    "Px-p---fx--i": "pronomen, indefinit pluralis femininum oklart kasus",
                    "Px-p---nn--i": "pronomen, indefinit pluralis neutrum nominativ",
                    "Px-p---ng--i": "pronomen, indefinit pluralis neutrum genitiv",
                    "Px-p---nd--i": "pronomen, indefinit pluralis neutrum dativ",
                    "Px-p---na--i": "pronomen, indefinit pluralis neutrum ackusativ",
                    "Px-p---nx--i": "pronomen, indefinit pluralis neutrum oklart kasus",
                    "Px-p---pn--i": "pronomen, indefinit pluralis utrum nominativ",
                    "Px-p---pd--i": "pronomen, indefinit pluralis utrum dativ",
                    "Px-p---xn--i": "pronomen, indefinit pluralis oklart genus nominativ",
                    "Px-p---xd--i": "pronomen, indefinit pluralis oklart genus dativ",
                    "Px-x---md--i": "pronomen, indefinit oklart numerus maskulinum dativ",
                    "Px-x---ng--i": "pronomen, indefinit oklart numerus neutrum genitiv",
                    "Py---------n": "determinerare, kvantor oböjlig",
                    "Py-s---mn--i": "determinerare, kvantor singularis maskulinum nominativ",
                    "Py-s---mg--i": "determinerare, kvantor singularis maskulinum genitiv",
                    "Py-s---md--i": "determinerare, kvantor singularis maskulinum dativ",
                    "Py-s---ma-si": "determinerare, kvantor singularis maskulinum ackusativ indefinit",
                    "Py-s---ma--i": "determinerare, kvantor singularis maskulinum ackusativ",
                    "Py-s---mx--i": "determinerare, kvantor singularis maskulinum oklart kasus",
                    "Py-s---fn--i": "determinerare, kvantor singularis femininum nominativ",
                    "Py-s---fg--i": "determinerare, kvantor singularis femininum genitiv",
                    "Py-s---fd--i": "determinerare, kvantor singularis femininum dativ",
                    "Py-s---fa--i": "determinerare, kvantor singularis femininum ackusativ",
                    "Py-s---fx--i": "determinerare, kvantor singularis femininum oklart kasus",
                    "Py-s---nn--i": "determinerare, kvantor singularis neutrum nominativ",
                    "Py-s---nd--i": "determinerare, kvantor singularis neutrum dativ",
                    "Py-s---na--i": "determinerare, kvantor singularis neutrum ackusativ",
                    "Py-s---nx-ti": "determinerare, kvantor singularis neutrum oklart kasus oklart species",
                    "Py-s---nx--i": "determinerare, kvantor singularis neutrum oklart kasus",
                    "Py-s---pn--i": "determinerare, kvantor singularis utrum nominativ",
                    "Py-s---xn--i": "determinerare, kvantor singularis oklart genus nominativ",
                    "Py-s---xa--i": "determinerare, kvantor singularis oklart genus ackusativ",
                    "Py-p---mn-si": "determinerare, kvantor pluralis maskulinum nominativ indefinit",
                    "Py-p---mn--i": "determinerare, kvantor pluralis maskulinum nominativ",
                    "Py-p---mg--i": "determinerare, kvantor pluralis maskulinum genitiv",
                    "Py-p---md-si": "determinerare, kvantor pluralis maskulinum dativ indefinit",
                    "Py-p---md--i": "determinerare, kvantor pluralis maskulinum dativ",
                    "Py-p---ma-si": "determinerare, kvantor pluralis maskulinum ackusativ indefinit",
                    "Py-p---ma--i": "determinerare, kvantor pluralis maskulinum ackusativ",
                    "Py-p---fn--i": "determinerare, kvantor pluralis femininum nominativ",
                    "Py-p---fg--i": "determinerare, kvantor pluralis femininum genitiv",
                    "Py-p---fd--i": "determinerare, kvantor pluralis femininum dativ",
                    "Py-p---fa--i": "determinerare, kvantor pluralis femininum ackusativ",
                    "Py-p---nn--i": "determinerare, kvantor pluralis neutrum nominativ",
                    "Py-p---nd--i": "determinerare, kvantor pluralis neutrum dativ",
                    "Py-p---na--i": "determinerare, kvantor pluralis neutrum ackusativ",
                    "Py-p---pa--i": "determinerare, kvantor pluralis utrum ackusativ",
                    "Py-p---on--i": "determinerare, kvantor pluralis icke-femininum nominativ",
                    "Py-p---xa--i": "determinerare, kvantor pluralis oklart genus ackusativ",
                    "Py-x---fn--i": "determinerare, kvantor oklart numerus femininum nominativ",
                    "Py-x---ng--i": "determinerare, kvantor oklart numerus neutrum genitiv",
                    "Py-x---xx--i": "determinerare, kvantor oklart numerus oklart genus oklart kasus",
                    "R----------n": "preposition oböjlig",
                    "V-1spia----i": "verb indikativ 1:e person singularis presens aktiv",
                    "V-2spia----i": "verb indikativ 2:e person singularis presens aktiv",
                    "V-2suia----i": "verb indikativ 2:e person singularis preteritum aktiv",
                    "V-2ppia----i": "verb indikativ 2:e person pluralis presens aktiv",
                    "V-3spia----i": "verb indikativ 3e person singularis presens aktiv",
                    "V-3spim----i": "verb indikativ 3e person singularis presens s-form",
                    "V-3suia----i": "verb indikativ 3e person singularis preteritum aktiv",
                    "V-3suim----i": "verb indikativ 3e person singularis preteritum s-form",
                    "V-3sxia----i": "verb indikativ 3e person singularis oklart tempus aktiv",
                    "V-3sxim----i": "verb indikativ 3e person singularis oklart tempus s-form",
                    "V-3ppia----i": "verb indikativ 3e person pluralis presens aktiv",
                    "V-3ppim----i": "verb indikativ 3e person pluralis presens s-form",
                    "V-3puia----i": "verb indikativ 3e person pluralis preteritum aktiv",
                    "V-3puim----i": "verb indikativ 3e person pluralis preteritum s-form",
                    "V-3pxia----i": "verb indikativ 3e person pluralis oklart tempus aktiv",
                    "V-3xpia----i": "verb indikativ 3e person oklart numerus presens aktiv",
                    "V-3xuia----i": "verb indikativ 3e person oklart numerus preteritum aktiv",
                    "V-3spsa----i": "verb konjunktiv 3e person singularis presens aktiv",
                    "V-3spsm----i": "verb konjunktiv 3e person singularis presens s-form",
                    "V-3susa----i": "verb konjunktiv 3e person singularis preteritum aktiv",
                    "V-3sxsa----i": "verb konjunktiv 3e person singularis oklart tempus aktiv",
                    "V-3ppsa----i": "verb konjunktiv 3e person pluralis presens aktiv",
                    "V-3ppsm----i": "verb konjunktiv 3e person pluralis presens s-form",
                    "V-3pusa----i": "verb konjunktiv 3e person pluralis preteritum aktiv",
                    "V-3pxsa----i": "verb konjunktiv 3e person pluralis oklart tempus aktiv",
                    "V-3xpsa----i": "verb konjunktiv 3e person oklart numerus presens aktiv",
                    "V-3spma----i": "verb imperativ 3e person singularis presens aktiv",
                    "V-3ppma----i": "verb imperativ 3e person pluralis presens aktiv",
                    "V--spp-mn-si": "verb particip singularis presens maskulinum nominativ indefinit",
                    "V--spp-mn-ti": "verb particip singularis presens maskulinum nominativ oklart species",
                    "V--spp-ma-si": "verb particip singularis presens maskulinum ackusativ indefinit",
                    "V--spp-mx-ti": "verb particip singularis presens maskulinum oklart kasus oklart species",
                    "V--spp-fn-ti": "verb particip singularis presens femininum nominativ oklart species",
                    "V--spp-nn-si": "verb particip singularis presens neutrum nominativ indefinit",
                    "V--spp-nn-ti": "verb particip singularis presens neutrum nominativ oklart species",
                    "V--spp-nd-ti": "verb particip singularis presens neutrum dativ oklart species",
                    "V--spp-na-si": "verb particip singularis presens neutrum ackusativ indefinit",
                    "V--spp-xx-ti": "verb particip singularis presens oklart genus oklart kasus oklart species",
                    "V--sup-mn-si": "verb particip singularis preteritum maskulinum nominativ indefinit",
                    "V--sup-mn-ti": "verb particip singularis preteritum maskulinum nominativ oklart species",
                    "V--sup-md-ti": "verb particip singularis preteritum maskulinum dativ oklart species",
                    "V--sup-ma-si": "verb particip singularis preteritum maskulinum ackusativ indefinit",
                    "V--sup-ma-ti": "verb particip singularis preteritum maskulinum ackusativ oklart species",
                    "V--sup-mx-ti": "verb particip singularis preteritum maskulinum oklart kasus oklart species",
                    "V--sup-fn-si": "verb particip singularis preteritum femininum nominativ indefinit",
                    "V--sup-fn-ti": "verb particip singularis preteritum femininum nominativ oklart species",
                    "V--sup-fx-ti": "verb particip singularis preteritum femininum oklart kasus oklart species",
                    "V--sup-nn-si": "verb particip singularis preteritum neutrum nominativ indefinit",
                    "V--sup-nn-ti": "verb particip singularis preteritum neutrum nominativ oklart species",
                    "V--sup-ng-ti": "verb particip singularis preteritum neutrum genitiv oklart species",
                    "V--sup-nd-ti": "verb particip singularis preteritum neutrum dativ oklart species",
                    "V--sup-na-si": "verb particip singularis preteritum neutrum ackusativ indefinit",
                    "V--sup-na-ti": "verb particip singularis preteritum neutrum ackusativ oklart species",
                    "V--sup-nx-si": "verb particip singularis preteritum neutrum oklart kasus indefinit",
                    "V--sup-nx-ti": "verb particip singularis preteritum neutrum oklart kasus oklart species",
                    "V--sup-px-ti": "verb particip singularis preteritum utrum oklart kasus oklart species",
                    "V--sup-xn-ti": "verb particip singularis preteritum oklart genus nominativ oklart species",
                    "V--ppp-mn-ti": "verb particip pluralis presens maskulinum nominativ oklart species",
                    "V--ppp-nn-ti": "verb particip pluralis presens neutrum nominativ oklart species",
                    "V--ppp-xn-ti": "verb particip pluralis presens oklart genus nominativ oklart species",
                    "V--pup-mn-ti": "verb particip pluralis preteritum maskulinum nominativ oklart species",
                    "V--pup-mg-ti": "verb particip pluralis preteritum maskulinum genitiv oklart species",
                    "V--pup-mx-ti": "verb particip pluralis preteritum maskulinum oklart kasus oklart species",
                    "V--pup-fn-si": "verb particip pluralis preteritum femininum nominativ indefinit",
                    "V--pup-fn-ti": "verb particip pluralis preteritum femininum nominativ oklart species",
                    "V--pup-fa-si": "verb particip pluralis preteritum femininum ackusativ indefinit",
                    "V--pup-nn-ti": "verb particip pluralis preteritum neutrum nominativ oklart species",
                    "V--pup-na-ti": "verb particip pluralis preteritum neutrum ackusativ oklart species",
                    "V--pup-xn-ti": "verb particip pluralis preteritum oklart genus nominativ oklart species",
                    "V--xpp-xx-ti": "verb particip oklart numerus presens oklart genus oklart kasus oklart species",
                    "V--xup-mn-ti": "verb particip oklart numerus preteritum maskulinum nominativ oklart species",
                    "V---pna----i": "verb infinitiv presens aktiv",
                    "V---pnm----i": "verb infinitiv presens s-form",
                    "V---una----i": "verb infinitiv preteritum aktiv",
                    "V-3spxa----i": "verb oklart modus 3e person singularis presens aktiv",
                    "V-3spxm----i": "verb oklart modus 3e person singularis presens s-form",
                    "V-3suxa----i": "verb oklart modus 3e person singularis preteritum aktiv",
                    "V-3ppxa----i": "verb oklart modus 3e person pluralis presens aktiv",
                    "V-3pxxa----i": "verb oklart modus 3e person pluralis oklart tempus aktiv"
                },                
                dataset: [
                    "A----------n",
                    "A--s---mnpsi",
                    "A--s---mnpti",
                    "A--s---mncsi",
                    "A--s---mncti",
                    "A--s---mnssi",
                    "A--s---mnswi",
                    "A--s---mnsti",
                    "A--s---mgpwi",
                    "A--s---mgpti",
                    "A--s---mgcti",
                    "A--s---mdpti",
                    "A--s---mapsi",
                    "A--s---mapti",
                    "A--s---macwi",
                    "A--s---macti",
                    "A--s---mxpsi",
                    "A--s---mxpti",
                    "A--s---mxcti",
                    "A--s---mxsti",
                    "A--s---fnpsi",
                    "A--s---fnpwi",
                    "A--s---fnpti",
                    "A--s---fncti",
                    "A--s---fnsti",
                    "A--s---fgpti",
                    "A--s---fdpti",
                    "A--s---fapsi",
                    "A--s---fapti",
                    "A--s---facti",
                    "A--s---fxpti",
                    "A--s---fxcti",
                    "A--s---nnpsi",
                    "A--s---nnpwi",
                    "A--s---nnpti",
                    "A--s---nncti",
                    "A--s---nnsti",
                    "A--s---ngpti",
                    "A--s---ndpti",
                    "A--s---ndsti",
                    "A--s---napsi",
                    "A--s---napti",
                    "A--s---nacti",
                    "A--s---nxpti",
                    "A--s---nxsti",
                    "A--s---pdpti",
                    "A--s---odpti",
                    "A--s---xnpti",
                    "A--s---xgpti",
                    "A--s---xdpti",
                    "A--s---xapti",
                    "A--s---xxpti",
                    "A--p---mnpsi",
                    "A--p---mnpti",
                    "A--p---mncti",
                    "A--p---mgpti",
                    "A--p---mdpti",
                    "A--p---mdcti",
                    "A--p---mapti",
                    "A--p---masti",
                    "A--p---mxpsi",
                    "A--p---fnpti",
                    "A--p---fdpsi",
                    "A--p---fdpti",
                    "A--p---fapsi",
                    "A--p---fapti",
                    "A--p---facti",
                    "A--p---fxpti",
                    "A--p---nnpti",
                    "A--p---nncti",
                    "A--p---ndpsi",
                    "A--p---ndpti",
                    "A--p---ndsti",
                    "A--p---napsi",
                    "A--p---napti",
                    "A--p---nacti",
                    "A--p---pncsi",
                    "A--p---ogpti",
                    "A--p---rdpti",
                    "A--p---xnpti",
                    "A--p---xdpsi",
                    "A--x---mnpti",
                    "A--x---mgpti",
                    "A--x---mapti",
                    "A--x---mxpti",
                    "A--x---fxpti",
                    "A--x---napti",
                    "A--x---xxpsi",
                    "A--x---xxpti",
                    "C----------n",
                    "Df---------n",
                    "Df-------p-i",
                    "Df-------c-i",
                    "Df-------s-i",
                    "Df-------x-i",
                    "Du---------n",
                    "F----------n",
                    "G----------n",
                    "I----------n",
                    "Nb-s---mn-si",
                    "Nb-s---mn-wi",
                    "Nb-s---mn-ti",
                    "Nb-s---mg-si",
                    "Nb-s---mg-wi",
                    "Nb-s---mg-ti",
                    "Nb-s---md-si",
                    "Nb-s---md-wi",
                    "Nb-s---md-ti",
                    "Nb-s---ma-si",
                    "Nb-s---ma-wi",
                    "Nb-s---ma-ti",
                    "Nb-s---mx-si",
                    "Nb-s---mx-ti",
                    "Nb-s---fn-si",
                    "Nb-s---fn-wi",
                    "Nb-s---fn-ti",
                    "Nb-s---fg-si",
                    "Nb-s---fg-wi",
                    "Nb-s---fg-ti",
                    "Nb-s---fd-si",
                    "Nb-s---fd-wi",
                    "Nb-s---fd-ti",
                    "Nb-s---fa-si",
                    "Nb-s---fa-wi",
                    "Nb-s---fa-ti",
                    "Nb-s---fx-si",
                    "Nb-s---fx-ti",
                    "Nb-s---nn-si",
                    "Nb-s---nn-wi",
                    "Nb-s---nn-ti",
                    "Nb-s---ng-si",
                    "Nb-s---ng-ti",
                    "Nb-s---nd-si",
                    "Nb-s---nd-wi",
                    "Nb-s---nd-ti",
                    "Nb-s---na-si",
                    "Nb-s---na-wi",
                    "Nb-s---na-ti",
                    "Nb-s---nx-si",
                    "Nb-s---nx-ti",
                    "Nb-s---pn-ti",
                    "Nb-s---pg-ti",
                    "Nb-s---pa-si",
                    "Nb-s---pa-ti",
                    "Nb-s---px-ti",
                    "Nb-s---on-ti",
                    "Nb-s---og-ti",
                    "Nb-s---od-ti",
                    "Nb-s---oa-ti",
                    "Nb-s---ox-ti",
                    "Nb-s---rn-ti",
                    "Nb-s---ra-ti",
                    "Nb-s---rx-ti",
                    "Nb-s---xn-ti",
                    "Nb-s---xg-si",
                    "Nb-s---xg-ti",
                    "Nb-s---xa-ti",
                    "Nb-p---mn-si",
                    "Nb-p---mn-wi",
                    "Nb-p---mn-ti",
                    "Nb-p---mg-wi",
                    "Nb-p---mg-ti",
                    "Nb-p---md-si",
                    "Nb-p---md-wi",
                    "Nb-p---md-ti",
                    "Nb-p---ma-si",
                    "Nb-p---ma-ti",
                    "Nb-p---mx-si",
                    "Nb-p---mx-ti",
                    "Nb-p---fn-si",
                    "Nb-p---fn-ti",
                    "Nb-p---fg-ti",
                    "Nb-p---fd-si",
                    "Nb-p---fd-ti",
                    "Nb-p---fa-si",
                    "Nb-p---fa-wi",
                    "Nb-p---fa-ti",
                    "Nb-p---fx-ti",
                    "Nb-p---nn-si",
                    "Nb-p---nn-wi",
                    "Nb-p---nn-ti",
                    "Nb-p---ng-si",
                    "Nb-p---ng-wi",
                    "Nb-p---ng-ti",
                    "Nb-p---nd-si",
                    "Nb-p---nd-wi",
                    "Nb-p---nd-ti",
                    "Nb-p---na-si",
                    "Nb-p---na-wi",
                    "Nb-p---na-ti",
                    "Nb-p---nx-si",
                    "Nb-p---nx-ti",
                    "Nb-p---pd-ti",
                    "Nb-p---pa-si",
                    "Nb-p---pa-ti",
                    "Nb-p---on-si",
                    "Nb-p---on-ti",
                    "Nb-p---og-ti",
                    "Nb-p---od-wi",
                    "Nb-p---od-ti",
                    "Nb-p---rd-si",
                    "Nb-p---rd-ti",
                    "Nb-x---mn-ti",
                    "Nb-x---mg-si",
                    "Nb-x---md-si",
                    "Nb-x---md-ti",
                    "Nb-x---ma-ti",
                    "Nb-x---mx-ti",
                    "Nb-x---fg-ti",
                    "Nb-x---fa-ti",
                    "Nb-x---fx-ti",
                    "Nb-x---nn-si",
                    "Nb-x---nn-ti",
                    "Nb-x---ng-ti",
                    "Nb-x---na-si",
                    "Nb-x---na-ti",
                    "Nb-x---nx-ti",
                    "Nb-x---ox-ti",
                    "Ne---------n",
                    "Ne-s---mn-ti",
                    "Ne-s---mg-ti",
                    "Ne-s---md-si",
                    "Ne-s---fd-si",
                    "Ne-s---xg-ti",
                    "Ne-s---xd-ti",
                    "Pd-s---mn--i",
                    "Pd-s---mg--i",
                    "Pd-s---md--i",
                    "Pd-s---ma--i",
                    "Pd-s---mx--i",
                    "Pd-s---fn--i",
                    "Pd-s---fg--i",
                    "Pd-s---fd--i",
                    "Pd-s---fa--i",
                    "Pd-s---fx--i",
                    "Pd-s---nn--i",
                    "Pd-s---ng--i",
                    "Pd-s---nd--i",
                    "Pd-s---na--i",
                    "Pd-s---nx--i",
                    "Pd-s---od--i",
                    "Pd-s---xn--i",
                    "Pd-s---xg--i",
                    "Pd-s---xx--i",
                    "Pd-p---mn--i",
                    "Pd-p---mg--i",
                    "Pd-p---md--i",
                    "Pd-p---ma--i",
                    "Pd-p---mx--i",
                    "Pd-p---fn--i",
                    "Pd-p---fg--i",
                    "Pd-p---fd--i",
                    "Pd-p---fa--i",
                    "Pd-p---nn--i",
                    "Pd-p---ng--i",
                    "Pd-p---nd--i",
                    "Pd-p---na--i",
                    "Pd-p---pn--i",
                    "Pd-p---pg--i",
                    "Pd-p---on--i",
                    "Pd-p---xn--i",
                    "Pd-p---xg--i",
                    "Pd-p---xd--i",
                    "Pd-p---xa--i",
                    "Pd-x---mn--i",
                    "Pd-x---mg--i",
                    "Pd-x---mx--i",
                    "Pd-x---fg--i",
                    "Pd-x---nx--i",
                    "Pd-x---xd--i",
                    "Pi-s---na--i",
                    "Pi-s---xn--i",
                    "Pi-s---xx--i",
                    "Pi-s----n--i",
                    "Pi-s----a--i",
                    "Pi-s----x--i",
                    "Pi-p----x--i",
                    "Pk-s----n--i",
                    "Pk-s----g--i",
                    "Pk-s----d--i",
                    "Pk-s----a--i",
                    "Pk-s----x--i",
                    "Pk-p----n--i",
                    "Pp-s----n--i",
                    "Pp-s----g--i",
                    "Pp-s----d--i",
                    "Pp-s----a--i",
                    "Pp-p----n--i",
                    "Pp-p----g--i",
                    "Pp-p----d--i",
                    "Pp-p----a--i",
                    "Pp-x----n--i",
                    "Ps-s----n--i",
                    "Ps-s----g--i",
                    "Ps-s----d--i",
                    "Ps-s----a--i",
                    "Ps-s----x--i",
                    "Ps-p----g--i",
                    "Ps-p----d--i",
                    "Ps-p----a--i",
                    "Ps-p----x--i",
                    "Ps-x----x--i",
                    "Px-s---mn--i",
                    "Px-s---mg--i",
                    "Px-s---md--i",
                    "Px-s---ma--i",
                    "Px-s---mx--i",
                    "Px-s---fn--i",
                    "Px-s---fd--i",
                    "Px-s---fa--i",
                    "Px-s---fx--i",
                    "Px-s---nn--i",
                    "Px-s---ng--i",
                    "Px-s---nd--i",
                    "Px-s---na--i",
                    "Px-s---nx--i",
                    "Px-s---pn--i",
                    "Px-s---rd--i",
                    "Px-s---xn--i",
                    "Px-s---xg--i",
                    "Px-p---mn--i",
                    "Px-p---md--i",
                    "Px-p---ma--i",
                    "Px-p---fn--i",
                    "Px-p---fd--i",
                    "Px-p---fa--i",
                    "Px-p---fx--i",
                    "Px-p---nn--i",
                    "Px-p---ng--i",
                    "Px-p---nd--i",
                    "Px-p---na--i",
                    "Px-p---nx--i",
                    "Px-p---pn--i",
                    "Px-p---pd--i",
                    "Px-p---xn--i",
                    "Px-p---xd--i",
                    "Px-x---md--i",
                    "Px-x---ng--i",
                    "Py---------n",
                    "Py-s---mn--i",
                    "Py-s---mg--i",
                    "Py-s---md--i",
                    "Py-s---ma-si",
                    "Py-s---ma--i",
                    "Py-s---mx--i",
                    "Py-s---fn--i",
                    "Py-s---fg--i",
                    "Py-s---fd--i",
                    "Py-s---fa--i",
                    "Py-s---fx--i",
                    "Py-s---nn--i",
                    "Py-s---nd--i",
                    "Py-s---na--i",
                    "Py-s---nx-ti",
                    "Py-s---nx--i",
                    "Py-s---pn--i",
                    "Py-s---xn--i",
                    "Py-s---xa--i",
                    "Py-p---mn-si",
                    "Py-p---mn--i",
                    "Py-p---mg--i",
                    "Py-p---md-si",
                    "Py-p---md--i",
                    "Py-p---ma-si",
                    "Py-p---ma--i",
                    "Py-p---fn--i",
                    "Py-p---fg--i",
                    "Py-p---fd--i",
                    "Py-p---fa--i",
                    "Py-p---nn--i",
                    "Py-p---nd--i",
                    "Py-p---na--i",
                    "Py-p---pa--i",
                    "Py-p---on--i",
                    "Py-p---xa--i",
                    "Py-x---fn--i",
                    "Py-x---ng--i",
                    "Py-x---xx--i",
                    "R----------n",
                    "V-1spia----i",
                    "V-2spia----i",
                    "V-2suia----i",
                    "V-2ppia----i",
                    "V-3spia----i",
                    "V-3spim----i",
                    "V-3suia----i",
                    "V-3suim----i",
                    "V-3sxia----i",
                    "V-3sxim----i",
                    "V-3ppia----i",
                    "V-3ppim----i",
                    "V-3puia----i",
                    "V-3puim----i",
                    "V-3pxia----i",
                    "V-3xpia----i",
                    "V-3xuia----i",
                    "V-3spsa----i",
                    "V-3spsm----i",
                    "V-3susa----i",
                    "V-3sxsa----i",
                    "V-3ppsa----i",
                    "V-3ppsm----i",
                    "V-3pusa----i",
                    "V-3pxsa----i",
                    "V-3xpsa----i",
                    "V-3spma----i",
                    "V-3ppma----i",
                    "V--spp-mn-si",
                    "V--spp-mn-ti",
                    "V--spp-ma-si",
                    "V--spp-mx-ti",
                    "V--spp-fn-ti",
                    "V--spp-nn-si",
                    "V--spp-nn-ti",
                    "V--spp-nd-ti",
                    "V--spp-na-si",
                    "V--spp-xx-ti",
                    "V--sup-mn-si",
                    "V--sup-mn-ti",
                    "V--sup-md-ti",
                    "V--sup-ma-si",
                    "V--sup-ma-ti",
                    "V--sup-mx-ti",
                    "V--sup-fn-si",
                    "V--sup-fn-ti",
                    "V--sup-fx-ti",
                    "V--sup-nn-si",
                    "V--sup-nn-ti",
                    "V--sup-ng-ti",
                    "V--sup-nd-ti",
                    "V--sup-na-si",
                    "V--sup-na-ti",
                    "V--sup-nx-si",
                    "V--sup-nx-ti",
                    "V--sup-px-ti",
                    "V--sup-xn-ti",
                    "V--ppp-mn-ti",
                    "V--ppp-nn-ti",
                    "V--ppp-xn-ti",
                    "V--pup-mn-ti",
                    "V--pup-mg-ti",
                    "V--pup-mx-ti",
                    "V--pup-fn-si",
                    "V--pup-fn-ti",
                    "V--pup-fa-si",
                    "V--pup-nn-ti",
                    "V--pup-na-ti",
                    "V--pup-xn-ti",
                    "V--xpp-xx-ti",
                    "V--xup-mn-ti",
                    "V---pna----i",
                    "V---pnm----i",
                    "V---una----i",
                    "V-3spxa----i",
                    "V-3spxm----i",
                    "V-3suxa----i",
                    "V-3ppxa----i",
                    "V-3pxxa----i"
                ]
            },
            annotation: {
                label: "annotation",
                extendedComponent: "datasetSelect",
                opts: liteOptions,
                dataset: [
                    "automatic",
                    "manual"
                ]
            }
        },
        structAttributes: {
            text_title: {label: "title"},
            section_name: {label: "section"},
            chapter_name: {label: "chapter"}
        }
    };
} // end if(isLab)

settings.corpusListing = new CorpusListing(settings.corpora);
